### PR TITLE
Add `/accounts/updateProfile` endpoint

### LINKED ISSUE #47: Add HTTP endpoints for updating and initially setting profile information
# Problem To Be Solved

The initial account registration does not ask for first and last name

## Motivation

The app will need more information for each user than just email in order to work. The user should thus be blocked from using the remainder of the app until they fill out this information. 

## Proposed Solution

Add back-end endpoints for initially setting and updating the profile information.

Suggested endpoints:
`POST /accounts/updateProfile`

### PR DESCRIPTION
**Pull request by kthchew**
# Issue
Close #47

# Description
Adds an `/accounts/updateProfile` endpoint that allows changing or setting the first and last name of an account. Accepts a JSON object literal in the following form:

```json
{
    "firstName": "",
    "lastName": ""
}
```

If `firstName` or `lastName` are empty strings, they will remain unchanged (they will not be set to empty strings).

# Type Of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Test Steps
Compile and run `api` then make the account

```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{"email": "testacct3@ufl.edu", "password": "helloworld"}' \
    localhost:8000/login/createAccount
```

get a token for it
```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{"email": "testacct3@ufl.edu", "password": "helloworld"}' \
    localhost:8000/login/validateAccount
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJMdW5jaEJ1ZGRpZXMiLCJzdWIiOiJ0ZXN0YWNjdDNAdWZsLmVkdSIsImV4cCI6MTY4MDMwMjcwOCwiaWF0IjoxNjgwMjE2MzA4fQ.zj6L0hEGBZ2AVb0LRtR4VKAtrv16H4XAMs8zyK48ENk
```

and modify its first and last name

```bash
curl -X POST -H "Content-Type: application/json" \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJMdW5jaEJ1ZGRpZXMiLCJzdWIiOiJ0ZXN0YWNjdDNAdWZsLmVkdSIsImV4cCI6MTY4MDMwMjcwOCwiaWF0IjoxNjgwMjE2MzA4fQ.zj6L0hEGBZ2AVb0LRtR4VKAtrv16H4XAMs8zyK48ENk" \
    -d '{"firstName": "test", "lastName": "test2"}' \
    localhost:8000/accounts/updateProfile
```

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by prayujt** [comment]
Instead of passing in the login and password in each request, perhaps we should migrate to using JWTs for authentication. For example, the result of validating the login could instead be returning a JWT, and they could pass this into every future request header to be authorized

**Comment by kthchew** [comment]
Makes sense, do you want that done in a separate PR first?

**Comment by prayujt** [comment]
Yes please, I can work on setting that part up over the weekend, though.

**Comment by prayujt** [comment]
Yes please, I can work on setting that part up over the weekend, though.

**Review by ercz16 — DISMISSED** [review]
Nice work

**Comment by kthchew** [comment]
@prayujt Ah, I've already written quite a bit of code needed for JWT to work. I'll make a different PR for that so you can look at that and use it as a base if you'd like

**Comment by prayujt** [comment]
No worries, you can go ahead and finish it up if you like then. I had just assumed you didn't start yet

**Comment by prayujt** [comment]
You can leave it in this PR if you like as well, and migrate this endpoint to use the new JWTs

**Comment by kthchew** [comment]
I only had time to make the helper methods for JWT, so I did that in #62 

I will see about migrating this PR to use that on Thursday

**Comment by kthchew** [comment]
this PR should be ready for review now
The test steps for this PR have also been updated

**Review by ercz16 — APPROVED** [review]

**Review by prayujt — APPROVED** [review]

**Pull request merged**
